/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdAnalysisRouteImport } from './routes/projects.$id.analysis'
import { Route as ProjectsIdCostRouteImport } from './routes/projects.$id.cost'
import { Route as ProjectsIdIotRouteImport } from './routes/projects.$id.iot'
import { Route as ProjectsIdMaterialsRouteImport } from './routes/projects.$id.materials'
import { Route as ProjectsIdProgressRouteImport } from './routes/projects.$id.progress'
import { Route as ProjectsIdQuantitiesRouteImport } from './routes/projects.$id.quantities'
import { Route as ProjectsIdUploadRouteImport } from './routes/projects.$id.upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdAnalysisRoute = ProjectsIdAnalysisRouteImport.update({
  id: '/$id/analysis',
  path: '/$id/analysis',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdCostRoute = ProjectsIdCostRouteImport.update({
  id: '/$id/cost',
  path: '/$id/cost',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdIotRoute = ProjectsIdIotRouteImport.update({
  id: '/$id/iot',
  path: '/$id/iot',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdMaterialsRoute = ProjectsIdMaterialsRouteImport.update({
  id: '/$id/materials',
  path: '/$id/materials',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdProgressRoute = ProjectsIdProgressRouteImport.update({
  id: '/$id/progress',
  path: '/$id/progress',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdQuantitiesRoute = ProjectsIdQuantitiesRouteImport.update({
  id: '/$id/quantities',
  path: '/$id/quantities',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdUploadRoute = ProjectsIdUploadRouteImport.update({
  id: '/$id/upload',
  path: '/$id/upload',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/analysis': typeof ProjectsIdAnalysisRoute
  '/projects/$id/cost': typeof ProjectsIdCostRoute
  '/projects/$id/iot': typeof ProjectsIdIotRoute
  '/projects/$id/materials': typeof ProjectsIdMaterialsRoute
  '/projects/$id/progress': typeof ProjectsIdProgressRoute
  '/projects/$id/quantities': typeof ProjectsIdQuantitiesRoute
  '/projects/$id/upload': typeof ProjectsIdUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/analysis': typeof ProjectsIdAnalysisRoute
  '/projects/$id/cost': typeof ProjectsIdCostRoute
  '/projects/$id/iot': typeof ProjectsIdIotRoute
  '/projects/$id/materials': typeof ProjectsIdMaterialsRoute
  '/projects/$id/progress': typeof ProjectsIdProgressRoute
  '/projects/$id/quantities': typeof ProjectsIdQuantitiesRoute
  '/projects/$id/upload': typeof ProjectsIdUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/analysis': typeof ProjectsIdAnalysisRoute
  '/projects/$id/cost': typeof ProjectsIdCostRoute
  '/projects/$id/iot': typeof ProjectsIdIotRoute
  '/projects/$id/materials': typeof ProjectsIdMaterialsRoute
  '/projects/$id/progress': typeof ProjectsIdProgressRoute
  '/projects/$id/quantities': typeof ProjectsIdQuantitiesRoute
  '/projects/$id/upload': typeof ProjectsIdUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/projects'
    | '/projects/new'
    | '/projects/'
    | '/projects/$id/analysis'
    | '/projects/$id/cost'
    | '/projects/$id/iot'
    | '/projects/$id/materials'
    | '/projects/$id/progress'
    | '/projects/$id/quantities'
    | '/projects/$id/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/projects/new'
    | '/projects'
    | '/projects/$id/analysis'
    | '/projects/$id/cost'
    | '/projects/$id/iot'
    | '/projects/$id/materials'
    | '/projects/$id/progress'
    | '/projects/$id/quantities'
    | '/projects/$id/upload'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/projects'
    | '/projects/new'
    | '/projects/'
    | '/projects/$id/analysis'
    | '/projects/$id/cost'
    | '/projects/$id/iot'
    | '/projects/$id/materials'
    | '/projects/$id/progress'
    | '/projects/$id/quantities'
    | '/projects/$id/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id/analysis': {
      id: '/projects/$id/analysis'
      path: '/$id/analysis'
      fullPath: '/projects/$id/analysis'
      preLoaderRoute: typeof ProjectsIdAnalysisRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id/cost': {
      id: '/projects/$id/cost'
      path: '/$id/cost'
      fullPath: '/projects/$id/cost'
      preLoaderRoute: typeof ProjectsIdCostRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id/iot': {
      id: '/projects/$id/iot'
      path: '/$id/iot'
      fullPath: '/projects/$id/iot'
      preLoaderRoute: typeof ProjectsIdIotRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id/materials': {
      id: '/projects/$id/materials'
      path: '/$id/materials'
      fullPath: '/projects/$id/materials'
      preLoaderRoute: typeof ProjectsIdMaterialsRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id/progress': {
      id: '/projects/$id/progress'
      path: '/$id/progress'
      fullPath: '/projects/$id/progress'
      preLoaderRoute: typeof ProjectsIdProgressRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id/quantities': {
      id: '/projects/$id/quantities'
      path: '/$id/quantities'
      fullPath: '/projects/$id/quantities'
      preLoaderRoute: typeof ProjectsIdQuantitiesRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id/upload': {
      id: '/projects/$id/upload'
      path: '/$id/upload'
      fullPath: '/projects/$id/upload'
      preLoaderRoute: typeof ProjectsIdUploadRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsIdAnalysisRoute: typeof ProjectsIdAnalysisRoute
  ProjectsIdCostRoute: typeof ProjectsIdCostRoute
  ProjectsIdIotRoute: typeof ProjectsIdIotRoute
  ProjectsIdMaterialsRoute: typeof ProjectsIdMaterialsRoute
  ProjectsIdProgressRoute: typeof ProjectsIdProgressRoute
  ProjectsIdQuantitiesRoute: typeof ProjectsIdQuantitiesRoute
  ProjectsIdUploadRoute: typeof ProjectsIdUploadRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsIdAnalysisRoute: ProjectsIdAnalysisRoute,
  ProjectsIdCostRoute: ProjectsIdCostRoute,
  ProjectsIdIotRoute: ProjectsIdIotRoute,
  ProjectsIdMaterialsRoute: ProjectsIdMaterialsRoute,
  ProjectsIdProgressRoute: ProjectsIdProgressRoute,
  ProjectsIdQuantitiesRoute: ProjectsIdQuantitiesRoute,
  ProjectsIdUploadRoute: ProjectsIdUploadRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
